FROM FROM golang:1.19.0-bullseye AS builder

ENV GO111MODULE=on
ENV GOFLAGS=-mod=vendor

WORKDIR /app

COPY src/ ./

RUN go mod download
RUN go mod verify
RUN go build -o /message_grpc_app ./server/cmd.go

FROM FROM golang:1.19.0-bullseye

RUN apk --no-cache add ca-certificates git

WORKDIR /

COPY --from=builder /message_grpc_app /message_grpc_app
EXPOSE 9000
CMD ["/message_grpc_app"]
