version: "3.9"

services:
  app:
    image: net.keithyw.messageapp/messageapp:latest
    container_name: message_app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
      DB: ${DB}
      DB_TIMEOUT_BASE: ${DB_TIMEOUT_BASE}
      COLLECTION: ${COLLECTION}
      PORT: ${PORT}
    networks:
      - backend
    ports:
      - "8081:8081"
    restart: on-failure

  grpc-app:
    image: net.keithyw.message.grpc.app/message-grpc-app:latest
    container_name: message_grpc_app
    build:
      dockerfile: Dockerfile.grpc
      context: .
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
      DB: ${DB}
      DB_TIMEOUT_BASE: ${DB_TIMEOUT_BASE}
      COLLECTION: ${COLLECTION}
      PORT: ${PORT}
    networks:
      - backend
    expose:
      - "9090"
    ports:
      - "9000:9000"  
    restart: always  

  mongodb:
    container_name: mongodb_service
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - backend

volumes:
  mongodata:

networks:
  backend:
    driver: bridge
